;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.dbg		file, "puts.c", 636, 1255247227
	.dbg		file, "../../include/stdio.h", 5964, 1255247211
	.dbg		file, "../../include/stddef.h", 2972, 1255247211
	.dbg		file, "../../include/stdarg.h", 2817, 1255247211
	.dbg		file, "../../include/string.h", 4883, 1255247211
	.dbg		file, "../../include/unistd.h", 3912, 1255247211
	.dbg		file, "./_file.h", 742, 1255247227
	.import		_stdout
	.export		_puts
	.import		_strlen
	.import		_write

; ---------------------------------------------------------------
; int __near__ __fastcall__ puts (__near__ const unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_puts: near

.segment	"DATA"

L0004:
	.byte	$0D

.segment	"CODE"

;
; {
;
	.dbg	line, "puts.c", 23
	jsr     pushax
;
; if (write (stdout->f_fd, s, strlen (s)) < 0 ||
;
	.dbg	line, "puts.c", 27
	jsr     decsp4
	lda     _stdout
	sta     ptr1
	lda     _stdout+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _strlen
	jsr     _write
	cpx     #$80
	bcs     L0014
;
; write (stdout->f_fd, &nl, 1)        < 0) {
;
	.dbg	line, "puts.c", 28
	jsr     decsp4
	lda     _stdout
	sta     ptr1
	lda     _stdout+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #<(L0004)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(L0004)
	sta     (sp),y
	ldx     #$00
	tya
	jsr     _write
	cpx     #$80
	bcc     L0006
;
; stdout->f_flags |= _FERROR;
;
	.dbg	line, "puts.c", 29
L0014:	lda     _stdout
	sta     ptr1
	lda     _stdout+1
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	ora     #$04
	sta     (ptr1),y
;
; return -1;
;
	.dbg	line, "puts.c", 30
	ldx     #$FF
	txa
	jmp     incsp2
;
; return 0;
;
	.dbg	line, "puts.c", 34
L0006:	ldx     #$00
	txa
;
; }
;
	.dbg	line, "puts.c", 35
	jmp     incsp2
	.dbg	line

.endproc

